package com.codeguardian.service;
import com.codeguardian.dto.*; import com.codeguardian.entity.*; import com.codeguardian.repository.*; import com.codeguardian.service.rules.RuleEngineService; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.nio.file.*; import java.util.*;
@Service @RequiredArgsConstructor public class ReviewService {
 private final ReviewTaskRepository taskRepository; private final FindingRepository findingRepository; private final CodeParserService parser; private final GitService gitService; private final RuleEngineService rules;
 @Transactional public ReviewResponseDTO createReviewTask(ReviewRequestDTO r){ if("GIT".equalsIgnoreCase(r.getReviewType())&&r.getProjectPath()==null)r.setProjectPath(gitService.cloneRepository(r.getGitUrl(),r.getGitUsername(),r.getGitPassword())); ReviewTask t=ReviewTask.builder().name(r.getTaskName()).reviewType(r.getReviewType()).scope(scope(r)).status("RUNNING").createdAt(LocalDateTime.now()).build(); t=taskRepository.save(t); try{review(t,r);t.setStatus("COMPLETED");t.setCompletedAt(LocalDateTime.now());}catch(Exception e){t.setStatus("FAILED");t.setErrorMessage(e.getMessage());} taskRepository.save(t);return ReviewResponseDTO.builder().taskId(t.getId()).taskName(t.getName()).reviewType(t.getReviewType()).status(t.getStatus()).createdAt(t.getCreatedAt()).message("Review task "+t.getStatus().toLowerCase()).build(); }
 public ReviewTask getTaskById(Long id){ return taskRepository.findById(id).orElseThrow(()->new IllegalArgumentException("Task not found: "+id)); }
 public List<FindingDTO> getFindingsByTaskId(Long id){ return findingRepository.findByTaskId(id).stream().map(f->FindingDTO.builder().id(f.getId()).severity(f.getSeverity()).title(f.getTitle()).location(f.getLocation()).startLine(f.getStartLine()).endLine(f.getEndLine()).description(f.getDescription()).suggestion(f.getSuggestion()).category(f.getCategory()).build()).toList(); }
 private String scope(ReviewRequestDTO r){ if(r.getCodeSnippet()!=null)return r.getCodeSnippet(); if(r.getFilePath()!=null)return r.getFilePath(); if(r.getDirectoryPath()!=null)return r.getDirectoryPath(); return r.getProjectPath(); }
 public List<ReviewResponseDTO> createDirectoryTasks(String directory,boolean project){return parser.readDirectoryParallel(directory).entrySet().stream().map(e->createReviewTask(ReviewRequestDTO.builder().taskName((project?"Project":"Directory")+": "+e.getKey()).reviewType(project?"PROJECT":"DIRECTORY").filePath(e.getKey()).codeSnippet(e.getValue()).rulesOnly(true).ruleTemplate("ALIBABA").build())).toList();}
 private void review(ReviewTask task,ReviewRequestDTO r){if("DIRECTORY".equalsIgnoreCase(r.getReviewType())||"PROJECT".equalsIgnoreCase(r.getReviewType())||"GIT".equalsIgnoreCase(r.getReviewType())){String root=Optional.ofNullable(r.getProjectPath()).orElse(r.getDirectoryPath());for(var entry:parser.readDirectoryParallel(root).entrySet())save(task,entry.getValue(),r,entry.getKey());}else{String code=r.getCodeSnippet();if((code==null||code.isBlank())&&r.getFilePath()!=null)try{code=Files.readString(Path.of(r.getFilePath()));}catch(Exception e){throw new IllegalArgumentException("Cannot read source file",e);}save(task,code,r,r.getFilePath());}}
 private void save(ReviewTask task,String code,ReviewRequestDTO r,String location){if(code==null||code.isBlank())throw new IllegalArgumentException("Code content is required");String template=Optional.ofNullable(r.getRuleTemplate()).orElse("ALIBABA");List<Finding> findings=rules.reviewWithTemplate(code,r.getLanguage(),template);findings.forEach(f->{f.setTask(task);if(location!=null)f.setLocation(location+": "+f.getLocation());});findingRepository.saveAll(findings);}
}
